/* eslint-disable */
// Generated by scripts/generate-seed.mjs — do not edit manually

import type { Category, Product } from './types'

export const SEED_CATEGORIES: Category[] = [
  {
    "id": 1,
    "slug": "dekorativnye-pokrytiya",
    "name": "Декоративные покрытия",
    "description": "Декоративные штукатурки, лазури и фактурные покрытия",
    "sortOrder": 1,
    "productCount": 39
  },
  {
    "id": 2,
    "slug": "interernye-kraski",
    "name": "Интерьерные краски",
    "description": "Краски для стен и потолков внутри помещений",
    "sortOrder": 2,
    "productCount": 16
  },
  {
    "id": 3,
    "slug": "fasadnye-kraski",
    "name": "Фасадные краски",
    "description": "Краски для наружных работ и фасадов",
    "sortOrder": 3,
    "productCount": 7
  },
  {
    "id": 4,
    "slug": "grunty",
    "name": "Грунты",
    "description": "Грунтовки и подготовительные составы",
    "sortOrder": 4,
    "productCount": 12
  },
  {
    "id": 5,
    "slug": "emali",
    "name": "Эмали и спецсоставы",
    "description": "Эмали, лаки и специализированные составы",
    "sortOrder": 5,
    "productCount": 3
  }
]

export const SEED_PRODUCTS: Product[] = [
  {
    "id": 1,
    "slug": "aura-dekor-lasur-color",
    "brand": "AURA DEKOR",
    "name": "Lasur Color",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "Lasur Color — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pasport_ Aura_Lasur Color.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 2,
    "slug": "aura-dekor-silk-glans-belarus",
    "brand": "AURA DEKOR",
    "name": "Silk Glans Belarus",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "Silk Glans Belarus — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pasport_ Aura_Silk Glans_Belarus.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 3,
    "slug": "aura-dekor-velour-silver-belarus",
    "brand": "AURA DEKOR",
    "name": "Velour Silver Belarus",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "Velour Silver Belarus — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pasport_ Aura_Velour Silver_Belarus.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 4,
    "slug": "aura-dekor-aktivare-solvent",
    "brand": "AURA DEKOR",
    "name": "Aktivare Solvent",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "Aktivare Solvent — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pasport_AURA_Aktivare_Solvent (1).pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 5,
    "slug": "aura-dekor-dekor-antik",
    "brand": "AURA DEKOR",
    "name": "Dekor Antik",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "Dekor Antik — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pasport_AURA_Dekor Antik.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 6,
    "slug": "aura-dekor-dekor-beton",
    "brand": "AURA DEKOR",
    "name": "Dekor Beton",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "Dekor Beton — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pasport_AURA_Dekor Beton.pdf"
    },
    "sizes": "",
    "price": null,
    "image": "/tech_list/AURA DEKOR/AURA DEKOR ART BETON/_thumb_550x550xin_upload_iblock_021_fke147epb3ily2r6ee5509vvukvm9qs1_Art Beton.png",
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 7,
    "slug": "aura-dekor-dekor-fantasi-3",
    "brand": "AURA DEKOR",
    "name": "Dekor Fantasi 3",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "Dekor Fantasi 3 — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pasport_AURA_Dekor Fantasi_3 (1).pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 8,
    "slug": "aura-dekor-dekor-jacquard-1",
    "brand": "AURA DEKOR",
    "name": "Dekor Jacquard 1",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "Dekor Jacquard 1 — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pasport_AURA_Dekor Jacquard_1.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 9,
    "slug": "aura-dekor-dekor-kontakt-100-2",
    "brand": "AURA DEKOR",
    "name": "Dekor Kontakt 100 2",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "Dekor Kontakt 100 2 — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pasport_AURA_Dekor Kontakt 100_2 (1).pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 10,
    "slug": "aura-dekor-dekor-kontakt-500-1",
    "brand": "AURA DEKOR",
    "name": "Dekor Kontakt 500 1",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "Dekor Kontakt 500 1 — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pasport_AURA_Dekor Kontakt 500_1_092021.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 11,
    "slug": "aura-dekor-dekor-oxid-metall",
    "brand": "AURA DEKOR",
    "name": "Dekor Oxid Metall",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "Dekor Oxid Metall — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pasport_AURA_Dekor Oxid_Metall.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 12,
    "slug": "aura-dekor-dekor-pasta-a1",
    "brand": "AURA DEKOR",
    "name": "Dekor Pasta a1",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "Dekor Pasta a1 — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pasport_AURA_Dekor Pasta a1.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 13,
    "slug": "aura-dekor-dekor-sanden-1",
    "brand": "AURA DEKOR",
    "name": "Dekor Sanden 1",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "Dekor Sanden 1 — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pasport_AURA_Dekor Sanden_1.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 14,
    "slug": "aura-dekor-dekor-sanden-glans",
    "brand": "AURA DEKOR",
    "name": "Dekor Sanden Glans",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "Dekor Sanden Glans — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pasport_AURA_Dekor Sanden_Glans.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 15,
    "slug": "aura-dekor-dekor-tempel",
    "brand": "AURA DEKOR",
    "name": "Dekor Tempel",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "Dekor Tempel — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pasport_AURA_Dekor Tempel.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 16,
    "slug": "aura-dekor-dekor-travertin",
    "brand": "AURA DEKOR",
    "name": "Dekor Travertin",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "Dekor Travertin — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pasport_AURA_Dekor Travertin.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 17,
    "slug": "aura-dekor-dekor-velour-matt-1",
    "brand": "AURA DEKOR",
    "name": "Dekor Velour Matt 1",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "Dekor Velour Matt 1 — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pasport_AURA_Dekor Velour Matt_1.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 18,
    "slug": "aura-dekor-dekor-venetian",
    "brand": "AURA DEKOR",
    "name": "Dekor Venetian",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "Dekor Venetian — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pasport_AURA_Dekor Venetian.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 19,
    "slug": "aura-dekor-dekor-citadell",
    "brand": "AURA DEKOR",
    "name": "Dekor Citadell",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "Dekor Citadell — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pasport_AURA_Dekor_Citadell.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 20,
    "slug": "aura-dekor-dekor-craquelure",
    "brand": "AURA DEKOR",
    "name": "Dekor Craquelure",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "Dekor Craquelure — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pasport_AURA_Dekor_Craquelure.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 21,
    "slug": "aura-dekor-dekor-lasur-halvglans",
    "brand": "AURA DEKOR",
    "name": "Dekor Lasur Halvglans",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "Dekor Lasur Halvglans — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pasport_AURA_Dekor_Lasur Halvglans.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 22,
    "slug": "aura-dekor-dekor-lasur-time-plus",
    "brand": "AURA DEKOR",
    "name": "Dekor Lasur Time Plus",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "Dekor Lasur Time Plus — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pasport_AURA_Dekor_Lasur Time Plus.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 23,
    "slug": "aura-dekor-dekor-lasur-matt",
    "brand": "AURA DEKOR",
    "name": "Dekor Lasur matt",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "Dekor Lasur matt — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pasport_AURA_Dekor_Lasur matt.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 24,
    "slug": "aura-dekor-dekor-sten-fasad",
    "brand": "AURA DEKOR",
    "name": "Dekor Sten Fasad",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "Dekor Sten Fasad — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pasport_AURA_Dekor_Sten Fasad.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 25,
    "slug": "aura-dekor-dekor-suede-1",
    "brand": "AURA DEKOR",
    "name": "Dekor Suede 1",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "Dekor Suede 1 — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pasport_AURA_Dekor_Suede_1.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 26,
    "slug": "aura-dekor-web-pass-aura-effekt-metall",
    "brand": "AURA DEKOR",
    "name": "WEB Pass AURA Effekt Metall",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "WEB Pass AURA Effekt Metall — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pass_AURA_Effekt_Metall_072024.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 27,
    "slug": "aura-dekor-web-pass-aura-lasur-extra-protect-glanz",
    "brand": "AURA DEKOR",
    "name": "WEB Pass AURA Lasur Extra Protect Glanz",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "WEB Pass AURA Lasur Extra Protect Glanz — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pass_AURA_Lasur Extra Protect Glanz_082024.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 28,
    "slug": "aura-dekor-web-pass-aura-lasur-extra-protect-matt",
    "brand": "AURA DEKOR",
    "name": "WEB Pass AURA Lasur Extra Protect Matt",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "WEB Pass AURA Lasur Extra Protect Matt — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pass_AURA_Lasur Extra Protect Matt_082024.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 29,
    "slug": "aura-dekor-web-pass-aura-soft",
    "brand": "AURA DEKOR",
    "name": "WEB Pass AURA Soft",
    "tagline": "AURA DEKOR · Декоративные покрытия",
    "description": "WEB Pass AURA Soft — профессиональный материал бренда AURA DEKOR. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "AURA DEKOR",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/AURA DEKOR/WEB_Pass_AURA_Soft_082024.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 30,
    "slug": "fabio-carbon",
    "brand": "FaBio",
    "name": "Carbon",
    "tagline": "FaBio · Декоративные покрытия",
    "description": "Carbon — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio-carbon.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 31,
    "slug": "fabio-fakturnaya-kraska",
    "brand": "FaBio",
    "name": "Fakturnaya Kraska",
    "tagline": "FaBio · Декоративные покрытия",
    "description": "Fakturnaya Kraska — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio-fakturnaya-kraska.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 32,
    "slug": "fabio-fassade-plus",
    "brand": "FaBio",
    "name": "Fassade Plus",
    "tagline": "FaBio · Фасадные краски",
    "description": "Fassade Plus — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Фасадные краски",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio-fassade-plus.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 3,
      "slug": "fasadnye-kraski",
      "name": "Фасадные краски"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 33,
    "slug": "fabio-fassade",
    "brand": "FaBio",
    "name": "Fassade",
    "tagline": "FaBio · Фасадные краски",
    "description": "Fassade — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Фасадные краски",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio-fassade.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 3,
      "slug": "fasadnye-kraski",
      "name": "Фасадные краски"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 34,
    "slug": "fabio-grund",
    "brand": "FaBio",
    "name": "Grund",
    "tagline": "FaBio · Грунты",
    "description": "Grund — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Грунты",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio-grund.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 4,
      "slug": "grunty",
      "name": "Грунты"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 35,
    "slug": "fabio-hybrid-fassadenfarbe",
    "brand": "FaBio",
    "name": "Hybrid Fassadenfarbe",
    "tagline": "FaBio · Фасадные краски",
    "description": "Hybrid Fassadenfarbe — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Фасадные краски",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio-hybrid-fassadenfarbe.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 3,
      "slug": "fasadnye-kraski",
      "name": "Фасадные краски"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 36,
    "slug": "fabio-multilack",
    "brand": "FaBio",
    "name": "Multilack",
    "tagline": "FaBio · Интерьерные краски",
    "description": "Multilack — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Интерьерные краски",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio-multilack.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 2,
      "slug": "interernye-kraski",
      "name": "Интерьерные краски"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 37,
    "slug": "fabio-samlatex-2",
    "brand": "FaBio",
    "name": "Samlatex 2",
    "tagline": "FaBio · Интерьерные краски",
    "description": "Samlatex 2 — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Интерьерные краски",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio-samlatex-2.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 2,
      "slug": "interernye-kraski",
      "name": "Интерьерные краски"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 38,
    "slug": "fabio-samlatex-3",
    "brand": "FaBio",
    "name": "Samlatex 3",
    "tagline": "FaBio · Интерьерные краски",
    "description": "Samlatex 3 — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Интерьерные краски",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio-samlatex-3.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 2,
      "slug": "interernye-kraski",
      "name": "Интерьерные краски"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 39,
    "slug": "fabio-samlatex-7",
    "brand": "FaBio",
    "name": "Samlatex 7",
    "tagline": "FaBio · Интерьерные краски",
    "description": "Samlatex 7 — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Интерьерные краски",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio-samlatex-7.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 2,
      "slug": "interernye-kraski",
      "name": "Интерьерные краски"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 40,
    "slug": "fabio-siliconputz",
    "brand": "FaBio",
    "name": "Siliconputz",
    "tagline": "FaBio · Декоративные покрытия",
    "description": "Siliconputz — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio-siliconputz.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 41,
    "slug": "fabio-solacryl-tiefgrund",
    "brand": "FaBio",
    "name": "Solacryl Tiefgrund",
    "tagline": "FaBio · Грунты",
    "description": "Solacryl Tiefgrund — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Грунты",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio-solacryl-tiefgrund.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 4,
      "slug": "grunty",
      "name": "Грунты"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 42,
    "slug": "fabio-special-primer",
    "brand": "FaBio",
    "name": "Special Primer",
    "tagline": "FaBio · Грунты",
    "description": "Special Primer — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Грунты",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio-special-primer.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 4,
      "slug": "grunty",
      "name": "Грунты"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 43,
    "slug": "fabio-tiefgrund",
    "brand": "FaBio",
    "name": "Tiefgrund",
    "tagline": "FaBio · Грунты",
    "description": "Tiefgrund — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Грунты",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio-tiefgrund.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 4,
      "slug": "grunty",
      "name": "Грунты"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 44,
    "slug": "fabio-ultra-matt",
    "brand": "FaBio",
    "name": "Ultra Matt",
    "tagline": "FaBio · Интерьерные краски",
    "description": "Ultra Matt — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Интерьерные краски",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio-ultra-matt.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 2,
      "slug": "interernye-kraski",
      "name": "Интерьерные краски"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 45,
    "slug": "fabio-art-beton",
    "brand": "FaBio",
    "name": "Art Beton",
    "tagline": "FaBio · Декоративные покрытия",
    "description": "Art Beton — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio_art-beton.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 46,
    "slug": "fabio-decor-lasur",
    "brand": "FaBio",
    "name": "Decor Lasur",
    "tagline": "FaBio · Декоративные покрытия",
    "description": "Decor Lasur — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio_decor-lasur.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 47,
    "slug": "fabio-emal-dlya-otopit-priborov",
    "brand": "FaBio",
    "name": "Emal Dlya Otopit. Priborov",
    "tagline": "FaBio · Эмали и спецсоставы",
    "description": "Emal Dlya Otopit. Priborov — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Эмали и спецсоставы",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio_emal-dlya-otopit.-priborov.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 5,
      "slug": "emali",
      "name": "Эмали и спецсоставы"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 48,
    "slug": "fabio-emal-univers-glyanczevaya",
    "brand": "FaBio",
    "name": "Emal Univers. Glyanczevaya",
    "tagline": "FaBio · Эмали и спецсоставы",
    "description": "Emal Univers. Glyanczevaya — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Эмали и спецсоставы",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio_emal-univers.-glyanczevaya.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 5,
      "slug": "emali",
      "name": "Эмали и спецсоставы"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 49,
    "slug": "fabio-emal-univers-matovaya",
    "brand": "FaBio",
    "name": "Emal Univers. Matovaya",
    "tagline": "FaBio · Эмали и спецсоставы",
    "description": "Emal Univers. Matovaya — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Эмали и спецсоставы",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio_emal-univers.-matovaya.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 5,
      "slug": "emali",
      "name": "Эмали и спецсоставы"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 50,
    "slug": "fabio-finish-pro",
    "brand": "FaBio",
    "name": "Finish Pro",
    "tagline": "FaBio · Интерьерные краски",
    "description": "Finish Pro — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Интерьерные краски",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio_finish-pro.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 2,
      "slug": "interernye-kraski",
      "name": "Интерьерные краски"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 51,
    "slug": "fabio-grunt-kvarczevyj",
    "brand": "FaBio",
    "name": "Grunt Kvarczevyj",
    "tagline": "FaBio · Грунты",
    "description": "Grunt Kvarczevyj — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Грунты",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio_grunt-kvarczevyj.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 4,
      "slug": "grunty",
      "name": "Грунты"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 52,
    "slug": "fabio-klebervlies-pro",
    "brand": "FaBio",
    "name": "Klebervlies Pro",
    "tagline": "FaBio · Грунты",
    "description": "Klebervlies Pro — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Грунты",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio_klebervlies-pro.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 4,
      "slug": "grunty",
      "name": "Грунты"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 53,
    "slug": "fabio-objekt-fassadenfarbe",
    "brand": "FaBio",
    "name": "Objekt Fassadenfarbe",
    "tagline": "FaBio · Фасадные краски",
    "description": "Objekt Fassadenfarbe — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Фасадные краски",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio_objekt-fassadenfarbe.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 3,
      "slug": "fasadnye-kraski",
      "name": "Фасадные краски"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 54,
    "slug": "fabio-objekt-interior",
    "brand": "FaBio",
    "name": "Objekt Interior",
    "tagline": "FaBio · Интерьерные краски",
    "description": "Objekt Interior — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Интерьерные краски",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio_objekt_interior.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 2,
      "slug": "interernye-kraski",
      "name": "Интерьерные краски"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 55,
    "slug": "fabio-schwarz",
    "brand": "FaBio",
    "name": "Schwarz",
    "tagline": "FaBio · Интерьерные краски",
    "description": "Schwarz — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Интерьерные краски",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio_schwarz.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 2,
      "slug": "interernye-kraski",
      "name": "Интерьерные краски"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 56,
    "slug": "fabio-seta",
    "brand": "FaBio",
    "name": "Seta",
    "tagline": "FaBio · Декоративные покрытия",
    "description": "Seta — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio_seta.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 57,
    "slug": "fabio-shtukaturka-koroed",
    "brand": "FaBio",
    "name": "Shtukaturka Koroed",
    "tagline": "FaBio · Декоративные покрытия",
    "description": "Shtukaturka Koroed — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio_shtukaturka-koroed.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 58,
    "slug": "fabio-shtukaturka-shuba",
    "brand": "FaBio",
    "name": "Shtukaturka Shuba",
    "tagline": "FaBio · Декоративные покрытия",
    "description": "Shtukaturka Shuba — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio_shtukaturka-shuba.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 59,
    "slug": "fabio-terreno-di-quarzo",
    "brand": "FaBio",
    "name": "Terreno Di Quarzo",
    "tagline": "FaBio · Декоративные покрытия",
    "description": "Terreno Di Quarzo — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio_terreno-di-quarzo.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 60,
    "slug": "fabio-travertino-naturale",
    "brand": "FaBio",
    "name": "Travertino Naturale",
    "tagline": "FaBio · Декоративные покрытия",
    "description": "Travertino Naturale — профессиональный материал бренда FaBio. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "FaBio",
      "Категория": "Декоративные покрытия",
      "Технический паспорт": "/tech_list/FaBio/tm_fabio_travertino-naturale.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 1,
      "slug": "dekorativnye-pokrytiya",
      "name": "Декоративные покрытия"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 61,
    "slug": "profitec-p-800-tiefgrund-acryl-hydrosol",
    "brand": "ProfiTec",
    "name": "P 800 Tiefgrund Acryl-Hydrosol",
    "tagline": "ProfiTec · Грунты",
    "description": "P 800 Tiefgrund Acryl-Hydrosol — профессиональный материал бренда ProfiTec. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "ProfiTec",
      "Категория": "Грунты",
      "Технический паспорт": "/tech_list/ProfiTec/Грунты/P 800 Tiefgrund Acryl-Hydrosol.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 4,
      "slug": "grunty",
      "name": "Грунты"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 62,
    "slug": "profitec-p-805-grundier-konzentrat-1-7",
    "brand": "ProfiTec",
    "name": "P 805 Grundier-Konzentrat 1 7",
    "tagline": "ProfiTec · Грунты",
    "description": "P 805 Grundier-Konzentrat 1 7 — профессиональный материал бренда ProfiTec. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "ProfiTec",
      "Категория": "Грунты",
      "Технический паспорт": "/tech_list/ProfiTec/Грунты/P 805 Grundier-Konzentrat 1 7.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 4,
      "slug": "grunty",
      "name": "Грунты"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 63,
    "slug": "profitec-p-818-grundierfarbe",
    "brand": "ProfiTec",
    "name": "P 818 Grundierfarbe",
    "tagline": "ProfiTec · Грунты",
    "description": "P 818 Grundierfarbe — профессиональный материал бренда ProfiTec. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "ProfiTec",
      "Категория": "Грунты",
      "Технический паспорт": "/tech_list/ProfiTec/Грунты/P 818 Grundierfarbe.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 4,
      "slug": "grunty",
      "name": "Грунты"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 64,
    "slug": "profitec-p305-allgrund",
    "brand": "ProfiTec",
    "name": "P305 Allgrund",
    "tagline": "ProfiTec · Грунты",
    "description": "P305 Allgrund — профессиональный материал бренда ProfiTec. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "ProfiTec",
      "Категория": "Грунты",
      "Технический паспорт": "/tech_list/ProfiTec/Грунты/P305 Allgrund.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 4,
      "slug": "grunty",
      "name": "Грунты"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 65,
    "slug": "profitec-p799-tiefgrund-acryl",
    "brand": "ProfiTec",
    "name": "P799 Tiefgrund Acryl",
    "tagline": "ProfiTec · Грунты",
    "description": "P799 Tiefgrund Acryl — профессиональный материал бренда ProfiTec. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "ProfiTec",
      "Категория": "Грунты",
      "Технический паспорт": "/tech_list/ProfiTec/Грунты/P799 Tiefgrund Acryl.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 4,
      "slug": "grunty",
      "name": "Грунты"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 66,
    "slug": "profitec-p817-q4-primer",
    "brand": "ProfiTec",
    "name": "P817 Q4 Primer",
    "tagline": "ProfiTec · Грунты",
    "description": "P817 Q4 Primer — профессиональный материал бренда ProfiTec. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "ProfiTec",
      "Категория": "Грунты",
      "Технический паспорт": "/tech_list/ProfiTec/Грунты/P817 Q4 Primer.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 4,
      "slug": "grunty",
      "name": "Грунты"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 67,
    "slug": "profitec-p101-volltonfarbe-schwarz",
    "brand": "ProfiTec",
    "name": "P101 Volltonfarbe schwarz",
    "tagline": "ProfiTec · Интерьерные краски",
    "description": "P101 Volltonfarbe schwarz — профессиональный материал бренда ProfiTec. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "ProfiTec",
      "Категория": "Интерьерные краски",
      "Технический паспорт": "/tech_list/ProfiTec/Интерьерная краска/P101 Volltonfarbe schwarz.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 2,
      "slug": "interernye-kraski",
      "name": "Интерьерные краски"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 68,
    "slug": "profitec-p118-rapidweiss",
    "brand": "ProfiTec",
    "name": "P118 Rapidweiss",
    "tagline": "ProfiTec · Интерьерные краски",
    "description": "P118 Rapidweiss — профессиональный материал бренда ProfiTec. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "ProfiTec",
      "Категория": "Интерьерные краски",
      "Технический паспорт": "/tech_list/ProfiTec/Интерьерная краска/P118 Rapidweiss.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 2,
      "slug": "interernye-kraski",
      "name": "Интерьерные краски"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 69,
    "slug": "profitec-p134-kerapaint-matt",
    "brand": "ProfiTec",
    "name": "P134 KeraPaint Matt",
    "tagline": "ProfiTec · Интерьерные краски",
    "description": "P134 KeraPaint Matt — профессиональный материал бренда ProfiTec. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "ProfiTec",
      "Категория": "Интерьерные краски",
      "Технический паспорт": "/tech_list/ProfiTec/Интерьерная краска/P134 KeraPaint Matt.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 2,
      "slug": "interernye-kraski",
      "name": "Интерьерные краски"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 70,
    "slug": "profitec-p136-kerapaint-color",
    "brand": "ProfiTec",
    "name": "P136 KeraPaint Color",
    "tagline": "ProfiTec · Интерьерные краски",
    "description": "P136 KeraPaint Color — профессиональный материал бренда ProfiTec. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "ProfiTec",
      "Категория": "Интерьерные краски",
      "Технический паспорт": "/tech_list/ProfiTec/Интерьерная краска/P136 KeraPaint Color.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 2,
      "slug": "interernye-kraski",
      "name": "Интерьерные краски"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 71,
    "slug": "profitec-p143-mattlatex-01",
    "brand": "ProfiTec",
    "name": "P143 Mattlatex 01",
    "tagline": "ProfiTec · Интерьерные краски",
    "description": "P143 Mattlatex 01 — профессиональный материал бренда ProfiTec. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "ProfiTec",
      "Категория": "Интерьерные краски",
      "Технический паспорт": "/tech_list/ProfiTec/Интерьерная краска/P143 Mattlatex 01.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 2,
      "slug": "interernye-kraski",
      "name": "Интерьерные краски"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 72,
    "slug": "profitec-p144-matt-plus",
    "brand": "ProfiTec",
    "name": "P144 Matt Plus",
    "tagline": "ProfiTec · Интерьерные краски",
    "description": "P144 Matt Plus — профессиональный материал бренда ProfiTec. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "ProfiTec",
      "Категория": "Интерьерные краски",
      "Технический паспорт": "/tech_list/ProfiTec/Интерьерная краска/P144 Matt Plus.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 2,
      "slug": "interernye-kraski",
      "name": "Интерьерные краски"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 73,
    "slug": "profitec-p154-samtlatex-10",
    "brand": "ProfiTec",
    "name": "P154 Samtlatex 10",
    "tagline": "ProfiTec · Интерьерные краски",
    "description": "P154 Samtlatex 10 — профессиональный материал бренда ProfiTec. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "ProfiTec",
      "Категория": "Интерьерные краски",
      "Технический паспорт": "/tech_list/ProfiTec/Интерьерная краска/P154 Samtlatex 10.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 2,
      "slug": "interernye-kraski",
      "name": "Интерьерные краски"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 74,
    "slug": "profitec-p235-universal-hausfarbe",
    "brand": "ProfiTec",
    "name": "P235 Universal Hausfarbe",
    "tagline": "ProfiTec · Интерьерные краски",
    "description": "P235 Universal Hausfarbe — профессиональный материал бренда ProfiTec. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "ProfiTec",
      "Категория": "Интерьерные краски",
      "Технический паспорт": "/tech_list/ProfiTec/Интерьерная краска/P235 Universal Hausfarbe.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 2,
      "slug": "interernye-kraski",
      "name": "Интерьерные краски"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 75,
    "slug": "profitec-p220-frontelast",
    "brand": "ProfiTec",
    "name": "P220 Frontelast",
    "tagline": "ProfiTec · Фасадные краски",
    "description": "P220 Frontelast — профессиональный материал бренда ProfiTec. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "ProfiTec",
      "Категория": "Фасадные краски",
      "Технический паспорт": "/tech_list/ProfiTec/Фасадные Краски/P220 Frontelast.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 3,
      "slug": "fasadnye-kraski",
      "name": "Фасадные краски"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 76,
    "slug": "profitec-fasadnye-kraski-p235-universal-hausfarbe",
    "brand": "ProfiTec",
    "name": "P235 Universal Hausfarbe",
    "tagline": "ProfiTec · Фасадные краски",
    "description": "P235 Universal Hausfarbe — профессиональный материал бренда ProfiTec. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "ProfiTec",
      "Категория": "Фасадные краски",
      "Технический паспорт": "/tech_list/ProfiTec/Фасадные Краски/P235 Universal Hausfarbe.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 3,
      "slug": "fasadnye-kraski",
      "name": "Фасадные краски"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  },
  {
    "id": 77,
    "slug": "profitec-p409-supersilicon",
    "brand": "ProfiTec",
    "name": "P409 SuperSilicon",
    "tagline": "ProfiTec · Фасадные краски",
    "description": "P409 SuperSilicon — профессиональный материал бренда ProfiTec. Подробные характеристики и условия применения указаны в техническом паспорте.",
    "features": [
      "Профессиональное качество",
      "Подробный технический паспорт"
    ],
    "specs": {
      "Бренд": "ProfiTec",
      "Категория": "Фасадные краски",
      "Технический паспорт": "/tech_list/ProfiTec/Фасадные Краски/P409 SuperSilicon.pdf"
    },
    "sizes": "",
    "price": null,
    "image": null,
    "isActive": true,
    "category": {
      "id": 3,
      "slug": "fasadnye-kraski",
      "name": "Фасадные краски"
    },
    "createdAt": "1970-01-01T00:00:00.000Z",
    "updatedAt": "1970-01-01T00:00:00.000Z"
  }
]
